### ISSUE TITLE
Deprecated selectors in `radioactive-syntax\index.less`

### ISSUE THREAD

**Issue by 1j01** [timglorioso/radioactive-syntax#1]
*(This is an auto generated issue report.)*

In `radioactive-syntax\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
:host` => `atom-text-editor,atom-text-editor`

* `atom-text-editor .wrap-guide,
:host .wrap-guide` => `atom-text-editor .wrap-guide,atom-text-editor .wrap-guide`

* `atom-text-editor .indent-guide,
:host .indent-guide` => `atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `atom-text-editor .invisible,
:host .invisible,
atom-text-editor .invisible-character,
:host .invisible-character` => `atom-text-editor .invisible,atom-text-editor .invisible,
atom-text-editor .invisible-character,atom-text-editor .invisible-character`

* `atom-text-editor .gutter,
:host .gutter` => `atom-text-editor .gutter,atom-text-editor .gutter`

* `atom-text-editor .gutter .line-number.cursor-line,
:host .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line`

* `atom-text-editor .gutter .line-number.git-line-added,
:host .gutter .line-number.git-line-added` => `atom-text-editor .gutter .line-number.git-line-added,atom-text-editor .gutter .line-number.git-line-added`

* `atom-text-editor .gutter .line-number.git-line-modified,
:host .gutter .line-number.git-line-modified` => `atom-text-editor .gutter .line-number.git-line-modified,atom-text-editor .gutter .line-number.git-line-modified`

* `atom-text-editor .gutter .line-number.git-line-removed:before,
:host .gutter .line-number.git-line-removed:before` => `atom-text-editor .gutter .line-number.git-line-removed:before,atom-text-editor .gutter .line-number.git-line-removed:before`

* `atom-text-editor .gutter .line-number.folded,
:host .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,
:host .gutter .line-number:after,
atom-text-editor .fold-marker:after,
:host .fold-marker:after` => `atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,atom-text-editor .gutter .line-number:after,
atom-text-editor .fold-marker:after,atom-text-editor .fold-marker:after`

* `atom-text-editor .cursor,
:host .cursor` => `atom-text-editor .cursor,atom-text-editor .cursor`

* `atom-text-editor .cursor-line,
:host .cursor-line` => `atom-text-editor .cursor-line,atom-text-editor .cursor-line`

* `atom-text-editor .highlight.selection .region,
:host .highlight.selection .region` => `atom-text-editor .highlight.selection .region,atom-text-editor .highlight.selection .region`

* `atom-text-editor .region.bracket-matcher,
:host .region.bracket-matcher` => `atom-text-editor .region.bracket-matcher,atom-text-editor .region.bracket-matcher`

* `atom-text-editor .source,
:host .source` => `atom-text-editor .syntax--source,atom-text-editor .syntax--source`

* `atom-text-editor .comment,
:host .comment,
atom-text-editor .source.embedded .comment,
:host .source.embedded .comment` => `atom-text-editor .syntax--comment,atom-text-editor .syntax--comment,
atom-text-editor .syntax--source.syntax--embedded .syntax--comment,atom-text-editor .syntax--source.syntax--embedded .syntax--comment`

* `atom-text-editor .entity,
:host .entity,
atom-text-editor .variable,
:host .variable` =>

**Comment by timglorioso** [comment]
fixed in 0317ff9
